shellEmulator: true

trustPolicy: no-downgrade

patchedDependencies:
  '@eslint/config-array': patches/@eslint__config-array.patch
catalog:
  '@antfu/eslint-config': ^7.6.1
  '@eslint/config-array': ^0.23.2
  '@iconify-json/carbon': ^1.2.19
  '@iconify-json/file-icons': ^1.2.2
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.72
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/twemoji': ^1.2.5
  '@iconify-json/vscode-icons': ^1.2.44
  '@nodelib/fs.walk': ^3.0.1
  '@nuxt/eslint': ^1.15.2
  '@shikijs/langs-precompiled': ^4.0.1
  '@shikijs/transformers': ^4.0.1
  '@types/connect': ^3.4.38
  '@types/ws': ^8.18.1
  '@typescript-eslint/utils': ^8.56.1
  '@unocss/eslint-config': ^66.6.7
  '@unocss/nuxt': ^66.6.7
  '@voxpelli/config-array-find-files': ^1.2.2
  '@vueuse/nuxt': ^14.2.1
  ansis: ^4.2.0
  bundle-require: ^5.1.0
  cac: ^7.0.0
  chokidar: ^5.0.0
  esbuild: ^0.27.3
  eslint: ^10.0.2
  find-up: ^8.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.2.0
  h3: ^1.15.5
  lint-staged: ^16.3.2
  minimatch: ^10.2.4
  mlly: ^1.8.0
  mrmime: ^2.0.1
  nitropack: ^2.13.1
  nuxt: ^4.3.1
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^11.0.0
  pathe: ^2.0.3
  rolldown: ^1.0.0-rc.6
  rollup: ^4.59.0
  shiki: ^4.0.1
  simple-git-hooks: ^2.13.1
  textmate-grammar-glob: ^0.0.1
  tinyglobby: ^0.2.15
  tsdown: ^0.16.8
  typescript: ^5.9.3
  vite: ^8.0.0-beta.16
  vitest: ^4.0.18
  vue-tsc: ^3.2.5
  ws: ^8.19.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
