packages: []
patchedDependencies:
  '@eslint/config-array': patches/@eslint__config-array.patch
catalog:
  '@antfu/eslint-config': ^4.13.3
  '@eslint/config-array': ^0.20.0
  '@iconify-json/carbon': ^1.2.9
  '@iconify-json/file-icons': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.37
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.22
  '@nodelib/fs.walk': ^3.0.1
  '@nuxt/eslint': ^1.4.1
  '@shikijs/langs-precompiled': ^3.6.0
  '@shikijs/transformers': ^3.6.0
  '@types/connect': ^3.4.38
  '@types/ws': ^8.18.1
  '@typescript-eslint/utils': ^8.33.1
  '@unocss/eslint-config': ^66.1.3
  '@unocss/nuxt': ^66.1.3
  '@voxpelli/config-array-find-files': ^1.2.2
  '@vueuse/nuxt': ^13.3.0
  ansis: ^4.1.0
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  debug: ^4.4.1
  esbuild: ^0.25.5
  eslint: ^9.30.0
  find-up: ^7.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  h3: ^1.15.3
  lint-staged: ^15.5.2
  minimatch: ^9.0.5
  mlly: ^1.7.4
  mrmime: ^2.0.1
  nitropack: ^2.11.12
  nuxt: ^3.17.5
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.2
  rollup: ^4.41.1
  shiki: ^3.6.0
  simple-git-hooks: ^2.13.0
  textmate-grammar-glob: ^0.0.1
  tinyglobby: ^0.2.14
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitest: ^3.2.2
  vue-tsc: ^2.2.10
  ws: ^8.18.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
