packages: []
patchedDependencies:
  '@eslint/config-array': patches/@eslint__config-array.patch
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@eslint/config-array': ^0.20.0
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/file-icons': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.31
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.19
  '@nodelib/fs.walk': ^3.0.1
  '@nuxt/eslint': ^1.3.0
  '@shikijs/langs-precompiled': ^3.2.2
  '@shikijs/transformers': ^3.2.2
  '@types/connect': ^3.4.38
  '@types/ws': ^8.18.1
  '@typescript-eslint/utils': ^8.29.1
  '@unocss/eslint-config': ^66.0.0
  '@unocss/nuxt': ^66.0.0
  '@voxpelli/config-array-find-files': ^1.2.2
  '@vueuse/nuxt': ^13.1.0
  ansis: ^3.17.0
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  debug: ^4.4.0
  esbuild: ^0.25.2
  eslint: ^9.24.0
  find-up: ^7.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  h3: ^1.15.1
  lint-staged: ^15.5.0
  minimatch: ^9.0.5
  mlly: ^1.7.4
  mrmime: ^2.0.1
  nitropack: ^2.11.8
  nuxt: ^3.16.2
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.0
  rollup: ^4.39.0
  shiki: ^3.2.2
  simple-git-hooks: ^2.12.1
  textmate-grammar-glob: ^0.0.1
  tinyglobby: ^0.2.12
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitest: ^3.1.1
  vue-tsc: ^2.2.8
  ws: ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
