packages: []
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@eslint/config-array': ^0.19.1
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/file-icons': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.20
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.10
  '@nodelib/fs.walk': ^3.0.1
  '@nuxt/eslint': ^0.7.5
  '@shikijs/langs-precompiled': ^1.27.0
  '@shikijs/transformers': ^1.26.2
  '@types/connect': ^3.4.38
  '@types/ws': ^8.5.13
  '@typescript-eslint/utils': ^8.20.0
  '@unocss/eslint-config': ^65.4.0
  '@unocss/nuxt': ^65.4.0
  '@voxpelli/config-array-find-files': ^1.2.2
  '@vueuse/nuxt': ^12.4.0
  ansis: ^3.15.0
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  debug: ^4.4.0
  esbuild: ^0.24.2
  eslint: ^9.18.0
  find-up: ^7.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  h3: ^1.13.1
  lint-staged: ^15.3.0
  minimatch: ^9.0.5
  mlly: ^1.7.4
  mrmime: ^2.0.0
  nitropack: 2.8.1
  nuxt: ^3.15.1
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.0
  shiki: ^1.27.0
  simple-git-hooks: ^2.11.1
  textmate-grammar-glob: ^0.0.1
  tinyglobby: ^0.2.11
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vitest: ^2.1.8
  vue-tsc: ^2.2.0
  ws: ^8.18.0
