packages: []
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@eslint/config-array': ^0.18.0
  '@iconify-json/carbon': ^1.2.3
  '@iconify-json/file-icons': ^1.2.0
  '@iconify-json/logos': ^1.2.3
  '@iconify-json/ph': ^1.2.1
  '@iconify-json/simple-icons': ^1.2.8
  '@iconify-json/svg-spinners': ^1.2.1
  '@iconify-json/twemoji': ^1.2.1
  '@iconify-json/vscode-icons': ^1.2.2
  '@nuxt/eslint': ^0.6.0
  '@shikijs/transformers': ^1.24.2
  '@types/connect': ^3.4.38
  '@types/ws': ^8.5.12
  '@typescript-eslint/utils': ^8.10.0
  '@unocss/eslint-config': ^0.63.4
  '@unocss/nuxt': ^0.63.4
  '@voxpelli/config-array-find-files': ^1.2.1
  '@vueuse/nuxt': ^11.1.0
  bundle-require: ^5.0.0
  cac: ^6.7.14
  chokidar: ^4.0.1
  esbuild: ^0.24.0
  eslint: ^9.16.0
  fast-glob: ^3.3.2
  find-up: ^7.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  h3: ^1.13.0
  lint-staged: ^15.2.10
  # v10.0 requires Node.js v20, so we stick with v9.0
  minimatch: ^9.0.5
  mlly: ^1.7.2
  mrmime: ^2.0.0
  nuxt: ^3.13.2
  nuxt-eslint-auto-explicit-import: ^0.1.0
  open: ^10.1.0
  picocolors: ^1.1.1
  shiki: ^1.24.2
  simple-git-hooks: ^2.11.1
  textmate-grammar-glob: ^0.0.1
  typescript: ^5.6.3
  unbuild: ^2.0.0
  vue-tsc: ^2.1.6
  ws: ^8.18.0
  nitropack: 2.8.1
